DROP TABLE IF EXISTS comercio;
CREATE DATABASE comercio;
USE comercio;


CREATE TABLE Categoria (
  Codigo INTEGER NOT NULL AUTO_INCREMENT,
  Descrição VARCHAR (50) NOT NULL,
  PRIMARY KEY(Codigo)
);

CREATE TABLE Produto (
  Codigo INTEGER NOT NULL AUTO_INCREMENT,
  Descrição VARCHAR (50) NOT NULL,
  Preço NUMERIC (10,2) NOT NULL,
  idCategoria INTEGER NOT NULL,
  PRIMARY KEY(Codigo)
);

CREATE TABLE Cliente (
  Codigo INTEGER NOT NULL AUTO_INCREMENT,
  Nome VARCHAR (50) NOT NULL,
  CPF INTEGER (11) NOT NULL,
  Nascimento DATE NOT NULL,
  PRIMARY KEY(Codigo)
);

CREATE TABLE Pedido (
  Numero INTEGER NOT NULL AUTO_INCREMENT,
  Data_2 DATE NOT NULL,
  Horário TIME NOT NULL,
  idCliente INTEGER NOT NULL,
  Status_2 CHAR(1) NULL,
  PRIMARY KEY(Numero)
);

CREATE TABLE Item (
  idProduto INTEGER NOT NULL,
  idPedido INTEGER NOT NULL,
  Quantidade INTEGER NOT NULL,
  Unitário NUMERIC (10,2) NULL,
  PRIMARY KEY(idProduto, idPedido)  
);

ALTER TABLE Produto ADD CONSTRAINT FK_Produto_Categoria
	FOREIGN KEY(idCategoria) REFERENCES Categoria(Codigo)
	On DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Pedido ADD CONSTRAINT FK_Pedido_Cliente
	FOREIGN KEY(idCliente) REFERENCES Cliente(Codigo)
	On DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Item ADD CONSTRAINT FK_Item_Pedido
	FOREIGN KEY(idPedido) REFERENCES Pedido(Numero)
	On DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE Item ADD CONSTRAINT FK_Item_Produto
	FOREIGN KEY(idProduto) REFERENCES Produto(Codigo)
	On DELETE RESTRICT ON UPDATE RESTRICT;




